// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5_owuHEIEtxiRG-V2VvPMIZASCsVBoMA',
    appId: '1:706613562156:web:dfcaad55385a907fa5fa89',
    messagingSenderId: '706613562156',
    projectId: 'techwiz5',
    authDomain: 'techwiz5.firebaseapp.com',
    storageBucket: 'techwiz5.appspot.com',
    measurementId: 'G-Z34CJ1XHX2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-PFjR6GGnrQOqrQpHdSM2yOA1QMohIEk',
    appId: '1:706613562156:android:79761e7937b2a332a5fa89',
    messagingSenderId: '706613562156',
    projectId: 'techwiz5',
    storageBucket: 'techwiz5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS5pC2EAV0XRH3mKrkwCcWJAP1SpcbGuU',
    appId: '1:706613562156:ios:06c32bae26944593a5fa89',
    messagingSenderId: '706613562156',
    projectId: 'techwiz5',
    storageBucket: 'techwiz5.appspot.com',
    iosBundleId: 'com.example.techwiz5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBS5pC2EAV0XRH3mKrkwCcWJAP1SpcbGuU',
    appId: '1:706613562156:ios:06c32bae26944593a5fa89',
    messagingSenderId: '706613562156',
    projectId: 'techwiz5',
    storageBucket: 'techwiz5.appspot.com',
    iosBundleId: 'com.example.techwiz5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5_owuHEIEtxiRG-V2VvPMIZASCsVBoMA',
    appId: '1:706613562156:web:005cb2bdc858e059a5fa89',
    messagingSenderId: '706613562156',
    projectId: 'techwiz5',
    authDomain: 'techwiz5.firebaseapp.com',
    storageBucket: 'techwiz5.appspot.com',
    measurementId: 'G-LV3QVF5E62',
  );
}
